- datasets/raw/dexjoco_raw_datasets_rand_full/bimanual_assembly
- datasets/raw/dexjoco_raw_datasets_rand_full/bimanual_hanoi
- datasets/raw/dexjoco_raw_datasets_rand_full/bimanual_microwave_cook
- datasets/raw/dexjoco_raw_datasets_rand_full/bimanual_photograph
- datasets/raw/dexjoco_raw_datasets_rand_full/bimanual_unlock_ipad
- datasets/raw/dexjoco_raw_datasets_rand_full/click_mouse
- datasets/raw/dexjoco_raw_datasets_rand_full/fold_glasses
- datasets/raw/dexjoco_raw_datasets_rand_full/hammer_nail
- datasets/raw/dexjoco_raw_datasets_rand_full/pick_bucket
- datasets/raw/dexjoco_raw_datasets_rand_full/pinch_tongs
- datasets/raw/dexjoco_raw_datasets_rand_full/water_plant
