bimanual_assembly:
  cameras:
    random_camera: random_camera
    wrist_left: wrist_left
    wrist_right: wrist_right
  action: action_rotvec
  state: state

bimanual_hanoi:
  cameras:
    random_camera: random_camera
    wrist_left: wrist_left
    wrist_right: wrist_right
  action: action_rotvec
  state: state

bimanual_microwave_cook:
  cameras:
    random_camera: random_camera
    wrist_left: wrist_left
    wrist_right: wrist_right
  action: action_rotvec
  state: state

bimanual_photograph:
  cameras:
    random_camera: random_camera
    wrist_left: wrist_left
    wrist_right: wrist_right
  action: action_rotvec
  state: state

bimanual_unlock_ipad:
  cameras:
    random_camera: random_camera
    wrist_left: wrist_left
    wrist_right: wrist_right
  action: action_rotvec
  state: state

click_mouse:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state

fold_glasses:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state

hammer_nail:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state

pick_bucket:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state

pinch_tongs:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state

water_plant:
  cameras:
    random_camera: random_camera
    wrist: wrist
  action: action_rotvec
  state: state
