- /data/weizhi_zhao/dexjoco/dexjoco_raw_datasets/randomize_data_scale500/bimanual_assembly
- /data/weizhi_zhao/dexjoco/dexjoco_raw_datasets/randomize_data_scale500/bimanual_hanoi
- /data/weizhi_zhao/dexjoco/dexjoco_raw_datasets/randomize_data_scale500/bimanual_unlock_ipad