bimanual_assembly:
  cameras:
    - ego
    - wrist_left
    - wrist_right
  action: action_rotvec
  state: state

bimanual_hanoi:
  cameras:
    - ego
    - wrist_left
    - wrist_right
  action: action_rotvec
  state: state

bimanual_microwave_cook:
  cameras:
    - ego
    - wrist_left
    - wrist_right
  action: action_rotvec
  state: state

bimanual_photograph:
  cameras:
    - ego
    - wrist_left
    - wrist_right
  action: action_rotvec
  state: state

bimanual_unlock_ipad:
  cameras:
    - ego
    - wrist_left
    - wrist_right
  action: action_rotvec
  state: state

click_mouse:
  cameras:
    - ego_right
    - wrist
  action: action_rotvec
  state: state

fold_glasses:
  cameras:
    - front
    - wrist
  action: action_rotvec
  state: state

hammer_nail:
  cameras:
    - front
    - wrist
  action: action_rotvec
  state: state

pick_bucket:
  cameras:
    - front
    - wrist
  action: action_rotvec
  state: state

pinch_tongs:
  cameras:
    - front
    - wrist
  action: action_rotvec
  state: state

water_plant:
  cameras:
    - front
    - wrist
  action: action_rotvec
  state: state
