- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/bimanual_assembly
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/bimanual_hanoi
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/bimanual_microwave_cook
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/bimanual_photograph
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/bimanual_unlock_ipad
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/click_mouse
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/fold_glasses
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/hammer_nail
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/pick_bucket
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/pinch_tongs
- /data0/weizhi_zhao/dexjoco/raw_datasets/datasets_v2/water_plant
