- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/bimanual_assembly
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/bimanual_hanoi
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/bimanual_microwave_cook
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/bimanual_photograph
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/bimanual_unlock_ipad
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/click_mouse
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/fold_glasses
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/hammer_nail
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/pick_bucket
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/pinch_tongs
- /data0/weizhi_zhao/dexjoco/raw_datasets/randomize_datasets/water_plant
